### ISSUE TITLE
[Bug]: native:serve throw command failed

### ISSUE THREAD

**Issue by valpuia** [NativePHP/laravel#160]
### What happened?

After trying to run `php artisan native:serve` then the following error came

```php
Error: Command failed: /home/valpuia/Private/Native PHP/native-3/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config
/home/valpuia/Private/Native PHP/native-3/vendor/nativephp/electron/resources/js/resources/php/php: 1: Syntax error: "(" unexpected

    at ChildProcess.exithandler (node:child_process:430:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12) {
  code: 2,
  killed: false,
  signal: null,
  cmd: '/home/valpuia/Private/Native PHP/native-3/vendor/nativephp/electron/resources/js/resources/php/php artisan native:config',
  stdout: '',
  stderr: '/home/valpuia/Private/Native PHP/native-3/vendor/nativephp/electron/resources/js/resources/php/php: 1: Syntax error: "(" unexpected\n'
}

API server started on port 4000

Starting PHP server... /home/valpuia/Private/Native PHP/native-3/vendor/nativephp/electron/resources/js/resources/php/php artisan serve /home/valpuia/Private/Native PHP/native-3

Making sure app folders are available

Skipping Database migration while in development.
You may migrate manually by running: php artisan native:migrate

libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

```

### How to reproduce the bug

Create new laravel project

`composer require nativephp/electron`

`php artisan native:install`

choose no when prompt "Would you like to start the NativePHP development server (yes/no) [no]:"

after that run `php artisan native:serve` manually

### Package Version

0.3.3

### PHP Version

8.2.8

### Laravel Version

10.18.0

### Node Version

18.13

### Which operating systems does with happen with?

Linux

**Comment by maurocasas** [comment]
Hey @valpuia , where you able to fix this?

**Comment by valpuia** [comment]
> Hey @valpuia , where you able to fix this?

Not yet, don't know where to fix actually.. will look more when I have free time

**Comment by keenminded** [comment]
In my case, the `native:config` command was undefined during `native:serve` execution. It is a little different from the error above. For some reason, it is not registering as the others.

If you look in the package code, all it does is encodes the Native PHP's own config file with `json_encode`. While the command is present in LoadStartupConfigurationCommand class, when I try to execute `php artisan native` it isn't found as part of the Native's artisan commands. To get around it, I opened `app/Console/Kernel.php` and added the lines below to the class:

```
protected $commands = [
    Native\Laravel\Commands\LoadStartupConfigurationCommand::class,
];
```

The error you are receiving may be due to the json_encode function or the config not being able to process the Native PHP configuration due to a mismatched parenthesis. I would try publishing the config file and checking it for errors in Tinker/Tinkerwell app by running the `json_encode(config('nativephp'));`

We are still in early Alpha, so there are plenty of bugs to go around. :)

**Comment by simonhamp** [comment]
Please update to nativephp/electron v0.6 and try again.
