### ISSUE TITLE
[Bug]: `error while loading shared libraries: libnss3.so` with laravel sail

### ISSUE THREAD

**Issue by ConrDev** [NativePHP/laravel#170]
### What happened?

I got this error after running `native:serve` while in `sail bash`

```bash
/var/www/html/vendor/nativephp/electron/resources/js/node_modules/electron/dist/electron: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
```

### How to reproduce the bug

install native php to laravel sail project and run `native:serve` while in `sail  bash`

### Package Version

0.4.0

### PHP Version

8.2.8

### Laravel Version

10.18.0

### Node Version

18.17.1

### Which operating systems does with happen with?

macOS

### Notes

Running Laravel sail image: `sail-8.1/app`
ubuntu 22.04

**Comment by AlexSBlackburn** [comment]
Getting the same issue, seems the Sail container is missing a bunch of packages. I tried manually installing them via `sail root-shell`, this was the eventual list:

- libnss3
- libatk1.0-0
- libatk-bridge2.0-0
- libgtk-3-0
- libgbm1
- libasound2

After that I ran in to the following two errors which don't seem solvable as an end user:

`[2003:0903/142826.146022:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /var/www/html/vendor/nativephp/electron/resources/js/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.`

And then after changing the mode of chrome-sandbox:

`[0903/143057.691572:FATAL:electron_main_delegate.cc(294)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.`

**Comment by sanyuanya** [comment]
I also encountered the same problem

**Comment by kolosz** [comment]
I encountered the same issue since the release of 0.1.0. Also opened an issue here but no answer yet. I tried the same steps that you described and got the exact same results. I would appreciate some help since I really want to use the package.

**Comment by simonhamp** [comment]
Sorry, but I don't have the capacity to support building via Sail - it's not something I use.

I highly recommend you try [Laravel Herd](https://herd.laravel.com) instead, at least for having a version of PHP running on your local machine that can be used to build NativePHP apps.

I'm using it and it's working great.
