### ISSUE TITLE
[Bug]: no such column in table error when running app after build

### ISSUE THREAD

**Issue by A3Brothers** [NativePHP/laravel#221]
### What happened?

Everything works fine when I am running my app in development with native:serve but when I build it for mac and try running it I get this no column error.
![database-error](https://github.com/NativePHP/laravel/assets/36996651/b341d92b-ba2c-4243-ac05-1e8f68dca9f5)

### How to reproduce the bug

you can try adding different fields like user_id inside user migration and use it inside application test it in dev environment the make a build and try.

### Package Version

0.4.0

### PHP Version

8.2.10 

### Laravel Version

10.28.0  

### Node Version

16.16.0  

### Which operating systems does with happen with?

macOS

**Comment by A3Brothers** [comment]
![reading-wrong-sqlite-file](https://github.com/NativePHP/laravel/assets/36996651/b69780eb-d06c-4b1d-b0eb-08178b5374b0)

In this image, you can see that the SQLite database file being built doesn't have the personal token and failed jobs table. However, in the built app, it indicates the presence of two additional tables, clearly suggesting that it is reading a different SQLite file. I am unable to determine the source of this file or the reason for this occurrence.

**Comment by simonhamp** [comment]
When you run a build, it stores various files in the user's "appdata" directory ([the exact location is platform-dependent](https://www.electronjs.org/docs/latest/api/app#appgetpathname)) - one of those is "their" copy of the database.

It's this version of the SQLite database that is lacking these columns.

This usually happens if you've changed the migrations after you've run a build.

The best option right now is to delete the database file from your app's appdata directory and re-run the build.

**Comment by simonhamp** [comment]
[There is a command to do this](https://nativephp.com/docs/digging-deeper/databases#refreshing-your-app-database), but it was broken.

That has now been fixed.

You can use the `nativephp:migrate:fresh` command to completely reinstate the 'prod' database from scratch.
