### ISSUE TITLE
[Bug]: php artisan native:install not working

### ISSUE THREAD

**Issue by mirzahaseebbaig** [NativePHP/laravel#35]
### What happened?

I'm trying to installing it on Laravel10 but it's stuck on `php artisan native:install`It's stuck on below line. 

**[14052:0721/201235.876:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is**

### How to reproduce the bug

npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> NativePHP@1.0.0 postinstall
> electron-builder install-app-deps

[main 2023-07-21T15:10:36.459Z] update#setState idle
[main 2023-07-21T15:10:40.813Z] WSL is not installed, so could not detect WSL profiles
[main 2023-07-21T15:11:06.480Z] update#setState checking for updates
[main 2023-07-21T15:11:06.673Z] update#setState idle
[14052:0721/201235.876:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

### Package Version

0.1.0

### PHP Version

8.1

### Laravel Version

10.5

### Which operating systems does with happen with?

Windows

**Comment by asepwaee** [comment]
I get same error here 

[main 2023-07-30T18:11:05.735Z] update#setState idle
[12740:0731/011108.464:ERROR:jump_list.cc(301)] Failed to append custom category 'Recent Folders' to Jump List due to system privacy settings.
[main 2023-07-30T18:11:08.492Z] updateWindowsJumpList#setJumpList unexpected result: customCategoryAccessDeniedError
[main 2023-07-30T18:11:35.850Z] update#setState checking for updates
[main 2023-07-30T18:11:37.129Z] update#setState idle
[14764:0731/011305.483:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

Package Version
0.1.0

PHP Version
8.1

Laravel Version
10.5

Which operating systems does with happen with?
Windows 10

Notes
No response

**Comment by rickyb1970** [comment]
I also have the same error message:

[main 2023-07-30T23:49:31.280Z] update#setState idle
[main 2023-07-30T23:49:32.571Z] WSL is not installed, so could not detect WSL profiles
[main 2023-07-30T23:50:01.292Z] update#setState checking for updates
[main 2023-07-30T23:50:01.417Z] update#setState idle
[16736:0731/075131.150:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

I have read in another forum that this has something to do with chrome settings which I am not familiar with. Any input is much appreciated.

Package Version
0.3.2

PHP Version
8.2

Laravel Version
10.5

Which operating systems does with happen with?
Windows 10

Notes
No response

**Comment by simonhamp** [comment]
A whole load of improvements to development and building on Windows have been made recently.

Please update to nativephp/electron v0.6 and try again.
