### ISSUE TITLE
[Bug]: php artisan native:install fails to publish config

### ISSUE THREAD

**Issue by Infamoustrey** [NativePHP/laravel#38]
### What happened?

The native:install command publishes the service provider but does not publish the `nativephp.php` config to the `config` folder. 

### How to reproduce the bug

Run the native:install command

### Package Version

current

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by Garanaw** [comment]
I think it might be something related to the package, or maybe to Spatie's LaravelPackageTools (used under the hood to publish files). I'm experiencing the same on Ubuntu:

PHP Version: 8.2
Laravel Version: 10
Which operating systems does with happen with? Linux Ubuntu 22.04.2 LTS

**Comment by encodiaweb** [comment]
Same here. Config file hasn't been published.

**Comment by pbvignesh** [comment]
I'm facing the same issue here as well. I'm not sure if it is an issue or if the code for it just hasn't been added (I might be wrong since I haven't taken a deeper look at this). But if you take a look at the electron backend repo at the file _**src/Commands/InstallCommand.php**_. You'll find the implementation of the _native:install_ command logic and all that is there is the following 



      
    public function handle()
    
    {
        
       $this->comment('Publishing NativePHP Service Provider...');
        
       $this->callSilent('vendor:publish', ['--tag' => 'nativephp-provider']);

        if ($this->option('force') || $this->confirm('Would you like to install the NativePHP NPM dependencies?', true)) {
            $this->installNpmDependencies();

            $this->output->newLine();
        }

        if (! $this->option('force') && $this->confirm('Would you like to start the NativePHP development server', false)) {
            $this->call('native:serve');
        }

        $this->info('NativePHP scaffolding installed successfully.');
    }

and the above piece of code just internally calls _vendor:publish_ and _native:serve_. I haven't taken a closer look there but from a quick glance I don't think there's any creation of a native config file there. Wondering if something should have been added there 🤔
