### ISSUE TITLE
[Bug]: native:serve opens app with devtools, hot reloading doesn't work

### ISSUE THREAD

**Issue by lpeterke** [NativePHP/laravel#63]
### What happened?

When I run native:serve it will launch my Laravel app in the app window, but with opened devtools.

If I then proceed to change something in welcome.blade.php, the changes are not reflected. 

Even stopping the dev server and running native:serve again doesn't help, I need to reboot my machine for the changes to take effect.

### How to reproduce the bug

laravel new native-example

Install nativePHP and run native:serve

### Package Version

0.1.1

### PHP Version

8.2.0

### Laravel Version

10.10

### Node Version

20.5.0

### Which operating systems does with happen with?

macOS

**Comment by PriceNathan** [comment]
Also getting issues related to this, with these error messages: 
(node:1204) electron: NSVisualEffectMaterialAppearanceBased has been deprecated and removed as of macOS 10.15.
(Use `Electron --trace-warnings ...` to show where the warning was created)

Skip checkForUpdates because application is not packed and dev update config is not forced

checkForUpdatesAndNotify called, downloadPromise is null

**Comment by multipacman** [comment]
A workaround to get the hot reload to trigger is to make changes on the `NativeAppServiceProvider.php` and save it. 

> I know this isn't what hot reload is supposed to be doing but for the time being this is better than stopping the dev server and running native:serve or rebooting the machine.

**Comment by lpeterke** [comment]
> But this is good that it runs it with devtools open no? :)

But I don't recall it being that way during the Laracon presentation. Plus, it's annoying that I have to manually close them all the time. Maybe the devtools only open automatically because Electron threw two warnings? But then again, where do these come from? I am on a fresh Laravel install where I didn't change anything yet...

>

**Comment by lpeterke** [comment]
> A workaround to get the hot reload to trigger is to make changes on the `NativeAppServiceProvider.php` and save it.
> 
> > I know this isn't what hot reload is supposed to be doing but for the time being this is better than stopping the dev server and running native:serve or rebooting the machine.

You are right! Changing the provider triggers a rebuild of the Electron App, but it still does not pick up any changes that I made to welcome.blade.php ...

**Comment by mpociot** [comment]
So hot reloading is automatically in place for the electron/app part. 
You can run yarn dev with vite in order to add frontend hot reloading. 

You can manually reload the route in your app by pressing CMD+R. 

Besides that, devtools open automatically while the app is in development mode. If you want to disable it, call the "showDevTools" method on the Window and pass false to it 👍

**Comment by lpeterke** [comment]
> So hot reloading is automatically in place for the electron/app part. You can run yarn dev with vite in order to add frontend hot reloading.
> 
> You can manually reload the route in your app by pressing CMD+R.
> 
> Besides that, devtools open automatically while the app is in development mode. If you want to disable it, call the "showDevTools" method on the Window and pass false to it 👍

Nice, ->showDevTools(false) did the trick!

Running "yarn run dev" also worked, but only after adding @vite('resources/js/app.js') to welcome.blade.php which was not there by default. It's also worth noticing, that it looks like you need to set up "yarn run dev" in a first terminal tab before doing "php artisan native:serve" in a second tab for it to work.

**Comment by Arcesilas** [comment]
Hi.  know this is a 1 year old issue, but I'd like to understand something...

> Besides that, devtools open automatically while the app is in development mode. If you want to disable it, call the "showDevTools" method on the Window and pass false to it 👍

If calling `showDevTools(false)` actually hides the dev tools, I've observed stange behaviours:
- shortcut `Ctrl+Shift+I` does not work when the devTools menu is not set
- in Window class' constructor, `showDevTools` is set to `config('app.debug')` which is true even when APP_DEBUG is set to false in `.env` (so is `env('APP_DEBUG')` at this point) => why and how does this happen? It seems this value is modified somewhere, because in Tinker, it is still `false`. This seems counter-intuitive to me and misleading when developing: how can I trust the `APP_DEBUG` I set in my `.env` file if something changes its value? How can I rely on it?
