### ISSUE TITLE
[Bug]: Main AppMenu does not show when you have MenuBar enabled

### ISSUE THREAD

**Issue by wattsie** [NativePHP/laravel#93]
### What happened?

When running a test harness with the following, the app menu shows, when you un-comment the MenuBar, the MenuBar appears, but the main App Menu does not show.

```
    public function boot(): void
    {
        Menu::new()
            ->appMenu()
            ->viewMenu()
            ->submenu(
                'About',
                Menu::new()
                    ->link('https://linux.com', 'Linux Yay')
                    ->link('https://google.com', 'Google Who')
            )
            ->register();

        // MenuBar::create()
        //     ->icon(resource_path('images/menuBarIcon.png'))
        //     // ->route('popup')
        //     // ->withContextMenu(
        //     //     Menu::new()
        //     //         ->label('My App')
        //     //         ->separator()
        //     //         ->link('https://wikileaks.org/', 'Learn more…')
        //     //         ->quit()
        //     // )
        //    ;
```

### How to reproduce the bug

```
laravel new test
cd test
composer require nativephp/electron
php artisan native:install --force
modify `app/Providers/NativeAppServiceProvider.php` to include menu
php artisan native:serve
```

### Package Version

0.3.2

### PHP Version

8.1.17 (bundled)

### Laravel Version

10.16.1

### Node Version

v20.5.0

### Which operating systems does with happen with?

macOS

### Notes

Not tested on other platforms atm, only MacOX x86

**Comment by simonhamp** [comment]
This is a figment of how MenuBar apps are constructed via Electron. You may find Apple's documentation around [Menu bar extras](https://developer.apple.com/design/human-interface-guidelines/the-menu-bar#Menu-bar-extras) useful reading.

When you use the `MenuBar` facade _without_ adding the `->showDockIcon()` switch, Electron creates what Apple calls a 'utility' app. Utility apps have no menu because they have no windows and are usually either a menu themselves or some sort of popover.

The `Menu` only appears for non-utility apps that have a Dock Icon associated with them. To achieve this, you need to chain the `->showDockIcon()` call onto your `MenuBar`:

```diff
    MenuBar::create()
        ->icon(resource_path('images/menuBarIcon.png'))
        ->route('popup')
        ->withContextMenu(
            Menu::new()
                ->label('My App')
                ->separator()
                ->link('https://wikileaks.org/', 'Learn more…')
                ->quit()
        )
-       ;
+      ->showDockIcon();
```

**Comment by wattsie** [comment]
Weird, that is totally strange, as I am sure I tested that as well.
BEBKEC, must have been asleep when testing it.
Many thanks.
